### ISSUE TITLE
ATM Rockhounding Lab Oven bucket consumption

### ISSUE THREAD

**Issue by Itty0** [AllTheMods/ATM-Expert#10]
Bucket will lost  by putting in to LabOven manually. 
Single bucket works fine, but multiple empty buckets will be lost except filled one.
ATM Ex-ver.1.0.30

**Comment by OrdinatorStouff** [comment]
just based on how shift+click versus manual placing works with empty buckets I think this is still a bug. I could not test with an actual "output" from the machine yet though
