### ISSUE TITLE
Creosote Oil not working

### ISSUE THREAD

**Issue by cpreh** [AllTheMods/ATM-Expert#101]
After updating my world from 1.1.0 to 1.1.1 I am no longer able to put creosote oil into buckets. The texture for the creosote oil fluid is missing and JEI says that creosote oil buckets are owned by Minecraft Forge.

This seems to be a compatibility issue with Railcraft which also registers creosote oil as a fluid and maybe also a bug in Minecraft Forge:
https://github.com/BluSunrize/ImmersiveEngineering/issues/1880

I was not able to resolve the issue simply by disabling creosote oil in Railcraft, so I don't know what to do now.

**Comment by goosezilla** [comment]
https://github.com/AllTheMods/ATM-Expert/issues/93
