### ISSUE TITLE
Can't extract creosote from coke oven.

### ISSUE THREAD

**Issue by donoya** [AllTheMods/ATM-Expert#109]
I tried putting the bucket in the top slot and it doesn't do anything. Shift clicking it in puts it in the same slot. Putting it into the bottom slot, it doesn't let me.

![image](https://user-images.githubusercontent.com/12679064/33354838-039caa80-d472-11e7-8de8-5082463ba5cd.png)

**Comment by donoya** [comment]
Never mind. After looking through the closed bugs, I found my issue. The issue should really be fixed by default for the pack.

**Comment by goosezilla** [comment]
I don't think that's possible but correct me if I'm wrong.

**Comment by donoya** [comment]
Something I've tried that seems to work is using the cans from forestry. So until the issue is resolved, something you could do is change the quest to need a creosote can, instead. Of course, I used the fluid transfer node into a forestry bottler to do it, but it might also work in the creosote oven directly.
