### ISSUE TITLE
[Expert.26] Botania Brewery not Craftable

### ISSUE THREAD

**Issue by BuggaNoia** [AllTheMods/ATM-Expert#11]
Put Recipe with (+) button in JEI into crafting table, but table didn't give me any result. (Output just kept blank, as there were no recipe for the pattern.)

There were no usage or something of any ingredient. All crafted directly before.
Test with AE2-Crafting Terminal, Crafting Station and Vanilla Crafting Table.
Test to remove some ingredient out of my inventory and Test JEI (+) again: The missing ingredient shown with red background and the button click wasn't accepted, so prior it was recognize right by JEI.
But all into grid by hand: Same result. (Mean no ;) )
Metadata prob.?

Version: .26

Extra Mods:
Optifine D4
OpenBlocks Elevators
ZyinHud
ChatLog

**Comment by OrdinatorStouff** [comment]
This was likely an issue with the spellbinding cloth not accepting anyDamage before and should have been fixed around 1.0.33

Please let me know if this is still a problem in pack version 1.1+ and we'll investigate farther.

**Comment by Viba** [comment]
Same thing happening for me in version 1.1.1.
