### ISSUE TITLE
Tinker's Hammer from Embers/Copper Hammer from Thermal Foundation Recipe Conflict

### ISSUE THREAD

**Issue by cgalliva** [AllTheMods/ATM-Expert#17]
Version: Alpha v1.0.31

As in the title, the recipes for the two hammers are the same and the Thermal Foundation one is what ends up being crafted

**Comment by OrdinatorStouff** [comment]
Thank you for reporting; it was actually a bigger deal that those thermal tools were craftable at all!

will be fixed in 1.1.1 (thermal tools recipes removed)
