### ISSUE TITLE
Updating a Server to 1.0.33b

### ISSUE THREAD

**Issue by elmigerj** [AllTheMods/ATM-Expert#18]
Hey!
I'm running a local server on 1.0.30 and would really like to update it to the new release. Unfortunately curse offers no 1.0.33b server zip in the additional files like there is for 1.0.30 and older releases (https://minecraft.curseforge.com/projects/all-the-mods-expert/files/2391282#additional-files). There's only the zip with an override folder and the new manifest.

So I've been trying to update my server manually, but had no success. What I tried was this:
First I deleted all my old mods and used a curse mod downloader on the new manifest.json file to get all the new versions of the mods.
Then I replaced the old config, scripts, etc with the new ones from the override folder.
When I started the server, deep resonance complained that one of its dependencies, eleccore 345, was missing, so I added that.
Starting the server again, FTBL now complains that it requires [Forge@[12.18.3.2254,)] which I assume is an updated forge version?
So, I suspect I'm doing something wrong here... What is the intended update procedure? Do I need to keep updating like this, step by step? Any help is appreciated :)

Thanks for the great pack by the way!

**Comment by iarspider** [comment]
Until the ATM team provides new server zip, do this in addition to replacing mods/configs/etc (*you need to be able to run commands on your server!*)

* Go to [Forge download page](https://files.minecraftforge.net/maven/net/minecraftforge/forge/index_1.10.2.html) for 1.10.2
* Click "Show all downloads", find the table row for version "12.18.3.2254", click on "Installer"
* Copy the downloaded file to your server and place it in the same directory as existing "forge.jar" file
* Run the installer: `java -jar forge-1.10.2-12.18.3.2254-installer.jar --installServer`
* Remove `forge.jar` and rename `forge-1.10.2-12.18.3.2254-universal.jar` to `forge.jar`

**Comment by elmigerj** [comment]
This worked perfectly, thanks!
