### ISSUE TITLE
 Recipe Suggestion: Copper Dust in Furnance/Alloy Smelter [Copy of ATM#436]

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-Expert#2]
https://github.com/whatthedrunk/allthemods/issues/436

**Comment by BuggaNoia** [comment]
Copper Dust should be handled as any other dust. Mean: Could be smelted into ingots in the same devices as the other dusts do.
Currently: Only smeltable in the TiC Smeltery

Version: .26
