### ISSUE TITLE
Crafting Camouflaged Paneling - Recipe Issue

### ISSUE THREAD

**Issue by Winrylive** [AllTheMods/ATM-Expert#20]
When crafting in the carpenter, the JEI recipe and the one configured in the carpenter call for red/yellow/blue dye in their respective slots but if I add just lapis, the craft is successful, using 6 lapis as if the other dyes aren't required. In a previous version, the yellow and red were required and since JEI still shows this recipe I'm guessing that something isn't working quite right.

**Comment by OrdinatorStouff** [comment]
Please let me know if this is still a problem in pack version 1.1+ and we'll investigate farther.

**Comment by Winrylive** [comment]
I'm sure it's still a problem because in Hypnotized's LP on YouTube he noticed the same issue.

**Comment by OrdinatorStouff** [comment]
Hypno is playing 1.0.33b not 1.1.x

But ATM:E is now considered "final" with 1.1.1+hotfix scripts.

We're still supporting issues if we can but there will probably not be future updates. ATME:Remastered is the packs successor that is now being developed instead.

**Comment by goosezilla** [comment]
It's vanilla forestry bug anyway so not much we could do. Especially as ct integration doesn't work properly to remove recipes.
