### ISSUE TITLE
Recipe conflict Iron Trapdoor and Iron Plate (Rail Craft)

### ISSUE THREAD

**Issue by Meller127** [AllTheMods/ATM-Expert#22]
Recipe conflict Iron Trapdoor and Iron Plate (Rail Craft)

The Iron Plates from RailCraft cant be crafted overriden by Iron Trapdoor.

ATM Expert 1.0.33b

**Comment by OrdinatorStouff** [comment]
I believe this is intentional; you need to use a rolling machine to craft the railcraft plates
