### ISSUE TITLE
ServerStart.sh restarts server when n to exit to shell is selected

### ISSUE THREAD

**Issue by MrMcCrab** [AllTheMods/ATM-Expert#24]
Installed ATM:Expert 1.0.33b server, when I stop the server I get this:
 Server will restart in ~10 seconds. No input needed...
Restart now (y) or exit to shell (n)
Answering n causes the server to restart, y will stop the server.

**Comment by Dijkstra1-zz** [comment]
This is fixed the latest version of the script should get updated with the next version of expert
