### ISSUE TITLE
Crash when placing Quantum Bridge on smooth sandstone

### ISSUE THREAD

**Issue by Meller127** [AllTheMods/ATM-Expert#25]
When placing a quantum bridge on smooth sandstone clients will crash with Tesselleting Block Model.

Tested on multiplayer server and Singelplayer creative

ATM Expert 1.0.33b
Crash log https://pastebin.com/U4RQ2aQk

**Comment by OrdinatorStouff** [comment]
I could not reproduce in latest pack version (1.1+)

Either you meant something other than the AE2 quantum ring or it's been fixed. Can you check/confirm with latest pack version (and a fresh profile in case it was Optifine or some other mod, too?)
