### ISSUE TITLE
Scripts not working on new 1.1.0 update 

### ISSUE THREAD

**Issue by OldManCraft** [AllTheMods/ATM-Expert#26]
Getting errors with scrips loading on server and single player.
Blood Magic 
Tinkers 
Forestry
Botania

![2017-06-23_09 00 23](https://user-images.githubusercontent.com/10180530/27490281-881b3864-57f2-11e7-8f5e-71bfe081c6d7.png)
![2017-06-23_09 02 19](https://user-images.githubusercontent.com/10180530/27490342-c58de61a-57f2-11e7-92dd-29077a73e5b4.png)

**Comment by OrdinatorStouff** [comment]
thanks for the report, I was aware of tinker/blood magic but not forestry/botania
1.1.0 was downgraded to Alpha for fixes, please check again when the next update comes out (likelt 1.1.1) and let me know if you're still seeing errors or not.

**Comment by OrdinatorStouff** [comment]
I haven't had any issues with forestry/botania that I've seen but I do have a problem with the calculator recipe for reinforced stone now registering properly in JEI (and also throwing an error in log)

going to just disable the "custom" recipe for it for now -- the calc is still required so the "gating" is still there but until I find a fix it'll be just cobble + planks for now

**Comment by OrdinatorStouff** [comment]
closing this and tracking Calc issue specifically in #27
