### ISSUE TITLE
Uncraftable Concrete

### ISSUE THREAD

**Issue by imadnsn** [AllTheMods/ATM-Expert#28]
I'm not sure if this is intended and I'm missing something here but it seems that concrete requires rebars from Railcraft which are only made from its Rolling Machine, however, the rolling machine requires steel/bronze, which cannot be made before coal coke, which in turn needs concrete. I saw that in the earlier youtube videos of ATM Expert the concrete only needed an iron and 4 bags of concrete, no rebar was required.

**Comment by OrdinatorStouff** [comment]
The rebar was an unexpected change, however it is obtainable with the manual rolling machine that does not need creosote. 

I will look into this in the next update but for now this is not critical as you SHOULD be able to still get there just with more iron and time spent in the manual rolling machine UI for now.

**Comment by imadnsn** [comment]
It does require at least coal coke to get the machines to make bronze/steel, which means I need something from the structure I'm trying to build.

**Comment by SiblisCu** [comment]
I have the same problem the manual rolling machine needs bronze for its gears.

**Comment by Graeter2** [comment]
I found that a naturally occurring Rolling Machine is possible to find *in villages with a railcraft structure* if you travel, unfortunately it is a circular recipe at the moment (1.1.1 beta) o/ best of luck

Edit: **

**Comment by OrdinatorStouff** [comment]
This will be fixed in pack version 1.1.2 -- expect update to curse in next day or two
