### ISSUE TITLE
Calculator Mod Recipes bug

### ISSUE THREAD

**Issue by Rublebuble** [AllTheMods/ATM-Expert#29]
Hey 
in JEI I can see the recipes for Redstone Ingot in the Scientific Calculator and Algorithm Separator (Iron Ingot + Redstone or only Redstone). Other recipes seems to have this bug to. (Only Calculator Mod)
Both are changed or Removed and don´t work. They are only showing in JEI, the new one is Working.

[Pics](http://imgur.com/a/76yVy)

this is an bug in the Mod itself:
https://github.com/SonarSonic/Calculator/issues/234
Mayits fixed in a newer Version for 1.10.2 (not in the old for 1.9.4)
Tested on SP/MP
Version 1.1.1 (beta)

**Comment by OrdinatorStouff** [comment]
This is the same problem as #27 I'm sure.

The problem with updating Sonar/Calc is that it usually breaks FAR more than what's fixed, especially with "expert" progression, and is why it has been avoided in almost all updates.

I'll work on it, however, and hopefully the transition is smooth(ish) if even possible at all.

**Comment by OrdinatorStouff** [comment]
This will be fixed in pack version 1.1.2 thanks to @BloodWorkXGaming writing a custom mod to handle Calc recipes
