### ISSUE TITLE
Concrete recipe broken

### ISSUE THREAD

**Issue by Amos10** [AllTheMods/ATM-Expert#33]
Hi,

i don't know if i am just too stupid for this, but it seems like the the recipe for the Block of Concrete is broken.
As of late it requires rebars. Rebars can only be made in a rolling machine, which needs bronze gears. But if you don't have a coke oven all the ways to make bronze are blocked off. And since you need Blocks of Concrete to make a coke oven, the early game progression in this modpack is broken.

Version: 1.1.1

**Comment by benkibejs** [comment]
#28 Duplicate, but no fix up yet though

**Comment by raelik** [comment]
As a temporary workaround on my server, I changed the manual rolling machine recipe to use copper gears instead of bronze, by putting this at the end of scripts/railcraft_expert.zs:
```
//====Manual Rolling Machine
recipes.remove(<railcraft:equipment>);
recipes.addShaped(<railcraft:equipment>, [[<ore:gearCopper>, <minecraft:piston>, <ore:gearCopper>],
                                          [<minecraft:piston>, <ore:workbench>, <minecraft:piston>],
                                          [<ore:gearCopper>, <minecraft:piston>, <ore:gearCopper>]]);
```

**Comment by OrdinatorStouff** [comment]
I've added a "hotfix" zip of scripts to the 1.1.1 pack curse page as additional file that addresses this.

Going forward, ATM:Expert 1.x is discontinued. The entire pack has been fully overhauled into something new entirely that we're banding "All The Mods Expert: Remastered"
