### ISSUE TITLE
Crash shortly after loading world

### ISSUE THREAD

**Issue by SiblisCu** [AllTheMods/ATM-Expert#40]
In remastered version
https://pastebin.com/dGAN8AB1

**Comment by MigukNamja** [comment]
If you haven't already, disable mipmap. You can do it via the Options menu or else by editing options.txt directly like so:

mipmapLevels:0

If that doesn't fix it, it's likely an OptiFine setting that's causing the issue. Here is my optionsof.txt (put in your base folder, the same folder that has options.txt):

https://pastebin.com/TunK3CEF
