### ISSUE TITLE
Changing mipmap from deafault 0 to 1 issue

### ISSUE THREAD

**Issue by SpeedSlider** [AllTheMods/ATM-Expert#41]
When I changed the mipmap settings from 0, which was the default setting, to 1 the menu text changed to the long text format (ex. of.options.CLEAR_WATER: OFF); basically of.options. showed up in front of all the text. Screenshots attached. Also, the main menu reverted to the no texture model (black and magenta). Screenshot also attached. If I changed mipmap back to 0 then the menu texted cleared up but not the main menu no texture model. If I restarted the client then the main menu was fine. I tried this twice to confirm it was repeatable. The only addition mod/texture pack I was running is Optifine E3.

![2017-08-19_19 43 56](https://user-images.githubusercontent.com/25437944/29490960-83b8a9be-851a-11e7-8625-c75d265840ce.png)
![2017-08-19_20 02 32](https://user-images.githubusercontent.com/25437944/29490959-83b81e0e-851a-11e7-98ea-bdefbc14ad33.png)

**Comment by MigukNamja** [comment]
This is a known issue and there's not much, i.e. not anything, we can do about it other than report it as an issue for OptiFine. OptiFine is closed source.
