### ISSUE TITLE
In ATMER v1.0.0, you can't make the Quest Book with a dirt.

### ISSUE THREAD

**Issue by chhaugen** [AllTheMods/ATM-Expert#42]
When other people join my server, they don't spawn with the Quest Book, and the only way to make one is by making a normal book first. Is this a bug or not?

**Comment by MigukNamja** [comment]
This will be fixed in the next release. For now, please put the following in scripts/miscellaneous_expert.zs

//=====Quest Book=====
val hqmQuestBook = <hardcorequesting:quest_book>;
recipes.addShapeless(hqmQuestBook, [<minecraft:dirt>]);
