### ISSUE TITLE
Processing issue

### ISSUE THREAD

**Issue by Waisse** [AllTheMods/ATM-Expert#43]
Early game issue : I can't smelt gold powder and cobalt dust.

**Comment by MigukNamja** [comment]
Waisse - this is by design. Gold powder requires at least a TiCo Smeltery to turn into ingots, blocks, nuggets, etc. Ditto cobalt. However, that needs to be more explicit. I'm thinking a tooltip would not be a bad idea.

Leaving this open so I remember to add the tooltip.

**Comment by Waisse** [comment]
It mess with my AA crusher setup. Can't you just make gold/cobalt ore not grindable and let the ability to smelt the dust ?

**Comment by MigukNamja** [comment]
Added tooltip. Must smelt in TiCo Smeltery or later mechanism. Copper dust is the same way, btw. It's not that hard to automate the TiCo smeltery. Just feed it lava and item pipe (hopper) in the dusts and put a redstone block (early game) above the drain. Later, you can use any kind of fluid pipe/conduit.

If we allow all these dusts to be vanilla smeltable, it breaks progression, i.e. allows you to bypass early game mechanics of the 'Expert' pack.

Tooltip will be available in next patch.
