### ISSUE TITLE
Possibly too-easy alloys in smeltery?

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-Expert#44]
Dark Steel, Signalum and maybe a couple other alloys can be made and cast in the Tinker's smeltery. Players have question if this is intended or not as it seems to bypass other gated methods.

**Comment by MigukNamja** [comment]
Fixed the signalum. I'll fix the dark steel as well. thanks.

**Comment by MigukNamja** [comment]
Hotfixed on server. Will make sure it's in next update.
