### ISSUE TITLE
Uncraftable hardened glass (unobtainable refined obsidian dust)

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-Expert#45]
ThermalExpansion_expert_recipes.zs

Hardened glass needs refined obsidian dust, but refined obsidian dust is unobtainable without having been able to get hardened glass first.

From "RyanTheBerry" on ATME:R official server:

> Currently playing ATM:E Remastered trying to progress and make the metallurgic infuser however it requires resonant fluxducts which if you follow the recipe down you need redstone energy fluxducts which require any BlockHardenedGlass however the only acceptable versions are fused quartz and TE Hardened glass fused quartz is alloy smelter only needing Mekanism to unlock and TE glass is in induction smelter which is gated further into the pack, but there are recipies that use the IE arc furnace, but they need refined obsidian dust which again is gated behind Mekanism. My question is, is there something im missing, or is this a bug? Fused quartz in the eio alloy smelter locked behind mek TE hardened glass in induction furnace locked behind DE which is in turn locked behind eio and TE hardened glass in the IE arc furnace which looks to be the method you are supposed to use, however the recipe requires refined obsidian dust which is locked behind Mek which you need the metallurgic infuser and osmium compressor

**Comment by MigukNamja** [comment]
Applied hotfix on Official Server. Will provide fix in next release.

**Comment by MigukNamja** [comment]
//=====metallurgic Infuser=====
//
recipes.remove(<mekanism:MachineBlock:8>);
val ic2BlastFurnace = <ic2:te:50>;
val hardenedFluxduct = <thermaldynamics:ThermalDynamics_0:1>;
recipes.addShaped(<mekanism:MachineBlock:8>,
[[<rockhounding_chemistry:alloyBItems:1>,<mekanism:BasicBlock>,<rockhounding_chemistry:alloyBItems:1>],
 [hardenedFluxduct,ic2BlastFurnace,hardenedFluxduct],
 [<rockhounding_chemistry:alloyBItems:1>,<mekanism:BasicBlock>,<rockhounding_chemistry:alloyBItems:1>]]);
