### ISSUE TITLE
Sickle droprates for flax

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-Expert#46]
Could be interaction between AA crops and Stone Sickle from extra util,

From Discord --

> @Cr1t1calReaper#6391 : (Remastered) Im using a Stone Sickle on about 30 full grown flax seed, and I get approx 12 stacks string and 5 stack seed. Is that intentional or a minor bug? Normal output when used on wheat

**Comment by MigukNamja** [comment]
Probably an AA and/or sickle bug. Sickle may work only on vanilla crops or AA may not respect sickle.
