### ISSUE TITLE
Quest only accepts Oak drying racks for completion

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-Expert#48]
Suggestion adding drying rack wood variants to a single oredict then adding a recipe to convert any drying rack wood type to oak (similar to doors/chests in misc_oredict_wood script)

**Comment by MigukNamja** [comment]
Fixed in 1.0.1, but *NOT* on server since that would reset everyone's HQM progress. Anytime a single HQM chapter .json is changed, it reset everyone's quest data.

**Comment by OrdinatorStouff** [comment]
The "conversion" recipe is another workaround/QoL option to consider as well.
