### ISSUE TITLE
Blaze Rod using Botania Alchemical Catalyst has competing outputs

### ISSUE THREAD

**Issue by SjaakRR** [AllTheMods/ATM-Expert#49]
http://imgur.com/a/F2bXx

mana pool crafts blaze into ember crystal and into nether wart with the alchemical catalyst,

**Comment by MigukNamja** [comment]
Fixed on Official Server just now by changing recipe from blaze rod/crystal to blaze powder/shard and adjusting mana cost accordingly. Sjaak verified the fix works.

//=====Botania way of getting ember
//
//mods.botania.ManaInfusion.addAlchemy(<embers:crystalEmber>, <minecraft:blaze_rod>, 2500);
//The recipe above conflicts with Botania's own blaze_rod-->nether_wart recipe, so using the recipe below instead:
mods.botania.ManaInfusion.addAlchemy(<embers:shardEmber>, <minecraft:blaze_powder>, 400);
