### ISSUE TITLE
Furnace from netherbrick

### ISSUE THREAD

**Issue by Mason11987** [AllTheMods/ATM-Expert#57]
JEI says 8 netherbricks makes a furnace, but instead it makes bakeware

**Comment by MigukNamja** [comment]
Fixed on Official Server and will provide fix in 1.0.2 . Use this until 1.0.2 is released:

scripts/miscellaneous_expert.zs
//=====Furnace=====
//
recipes.remove(vanillaFurnace);
recipes.addShaped(vanillaFurnace,
[[driedBricks,driedBricks,driedBricks],
 [driedBricks,<ore:cobblestone>,driedBricks],
 [driedBricks,driedBricks,driedBricks]]);

recipes.addShaped(vanillaFurnace,
[[<minecraft:netherbrick>,<minecraft:netherbrick>,<minecraft:netherbrick>],
 [<minecraft:netherbrick>,<ore:cobblestone>,<minecraft:netherbrick>],
 [<minecraft:netherbrick>,<minecraft:netherbrick>,<minecraft:netherbrick>]]);

**Comment by MigukNamja** [comment]
Also, you can 'fix' this issue on 1.0.1 without any script changes by clicking on the button at the bottom right of your vanilla crafting able to access additional/alternative recipes.

Click [here](http://i.imgur.com/rI2Gt6j.png) to see picture.

**Comment by Mason11987** [comment]
Neat, thanks!
