### ISSUE TITLE
Rockhounding causing crashes

### ISSUE THREAD

**Issue by topher2010** [AllTheMods/ATM-Expert#59]
https://pastebin.com/rjFTwHEq

Happened twice so far with using rockhounding to process items to get shards.

**Comment by MigukNamja** [comment]
topher2010, can you describe a little more what you were doing, i.e. what action with what machine (mineral analyzer)? Mod author will need to reproduce the crash.

**Comment by topher2010** [comment]
it was the Leaching Vat causing the issue.  I tried to place an empty bucket into the slot for sulfuric acid seeing if i could take a bucket out of the machine when the crash happened.

**Comment by Ravalli03** [comment]
Have the same issue, placing an empty bucket in to rocking machines causes game to crash

**Comment by goosezilla** [comment]
should be fixed with updated versions
