### ISSUE TITLE
Crash after using "Merge to nearby chests"

### ISSUE THREAD

**Issue by Mason11987** [AllTheMods/ATM-Expert#62]
https://paste.ubuntu.com/25421762/

Crash at line 1200.

I used this many times and now it's causing a crash, on both the previous version and 1.1.0 which I just installed.

I have nothing in my inventory (I might have a bauble, but I did it many times with that in place).

Looks like it may be related to the auto-anvil possibly, so not sure if I should post there, or to quark, or here.

Edit - Just tested moving the anvil, no crash.

Thanks!

**Comment by MigukNamja** [comment]
Yeah, we've had to disable a couple of OpenBlocks so far due to crashes. It's not a very stable mod/port. I'll leave this open to think about disabling the auto-anvil.

**Comment by Boomflex** [comment]
Non reproducible. 

Update to 1.1.1 and let us know.
