### ISSUE TITLE
Transfer nodes causing crash

### ISSUE THREAD

**Issue by formant84** [AllTheMods/ATM-Expert#64]
Game crashes instantly when inserting mining upgrade into extra utilities transfer node (both fluid and item varieties)

**Comment by MigukNamja** [comment]
Please attach or link to a/your client or server crash log, please.

**Comment by firedoom13** [comment]
Same here but with speed upgrades:
[crash-2017-08-30_20.15.36-client.txt](https://github.com/AllTheMods/ATM-Expert/files/1265399/crash-2017-08-30_20.15.36-client.txt)

**Comment by mulch75** [comment]
Upgrade to 1.6 still same problem, downgrade to 1.5.1 problem resolved for now!

**Comment by goosezilla** [comment]
should be fixed in newer versions of extra utils so closing for now
