### ISSUE TITLE
[Suggestion] Osmiridium Recipe in Arc Furnace?

### ISSUE THREAD

**Issue by Vyraal1** [AllTheMods/ATM-Expert#65]
Would it be possible to add an Osmiridium ingot recipe in the Arc Furnace? Currently the only way to get it is through the smeltery, and it would make sense progression wise to be able to make them in the Arc Furnace (prefer AF over EIO Alloy Smelter as you can control the energy requirements better).

**Comment by goosezilla** [comment]
done
