### ISSUE TITLE
Psi Block Duplication

### ISSUE THREAD

**Issue by Darklight-03** [AllTheMods/ATM-Expert#68]
using a basic block break trick on any thermal expansion machine drops the original machine, in addition to the machine with the same id but data value of 0

All grey machines drop redstone furnaces
All blue machines drop aqueous accumulators
All dynamos drop steam dynamos
etc.

and this is in addition to the original machine, even if you break for example, an aqueous accumulator, you will get 2.

for reference, [this](https://puu.sh/xoJTZ/a5418e348f.png) is the extremely basic spell i am using that causes this. 

Not sure if this is a psi issue or a thermal expansion issue, or some strange interaction. Psi does not appear to duplicate any other mods blocks, and thermal expansion does not appear to be duplicated by anything else.

(edit: mfr machines are also duplicated by psi, it seems to be a problem with psi)

**Comment by Ricket** [comment]
Looks like it has been a known Psi issue for many months, sadly.

https://github.com/Vazkii/Psi/issues/353 

https://github.com/Vazkii/Psi/issues/343

https://github.com/Vazkii/Psi/issues/335

**Comment by spdkils** [comment]
Also dups heads. :O Want wither heads... ?
