### ISSUE TITLE
All Mod suggestions [Copy of ATM#327]

### ISSUE THREAD

**Issue by ghost** [AllTheMods/ATM-Expert#7]
Here are all the mods that have been suggested for the pack, feel free to suggest more.

[Refraction](https://mods.curse.com/mc-mods/minecraft/253578-refraction)
[Totemic](https://minecraft.curseforge.com/projects/totemic)
[Better With Mods](https://minecraft.curseforge.com/projects/better-with-mods)
[Abyssalcraft Integration](https://mods.curse.com/mc-mods/minecraft/234851-abyssalcraft-integration)
[Agricraft](https://minecraft.curseforge.com/projects/agricraft)
[Simple Void World](https://mods.curse.com/mc-mods/minecraft/254466-simple-void-world)
[Mod Name Tooltip](https://minecraft.curseforge.com/projects/mod-name-tooltip)
[ImmersiveCraft](https://minecraft.curseforge.com/projects/immersive-craft)
[Aqua Mundi](https://minecraft.curseforge.com/projects/aqua-munda)
[OpenBlocks Elevator](https://minecraft.curseforge.com/projects/openblocks-elevator)
[Advanced Machines](https://minecraft.curseforge.com/projects/advanced-machines?gameCategorySlug=mc-mods&projectID=251205)
[Vitality](https://minecraft.curseforge.com/projects/vitality)
[Open Glider](https://minecraft.curseforge.com/projects/open-glider)  
[Just Enough Dimensions](https://minecraft.curseforge.com/projects/just-enough-dimensions)  
[Computronics](http://wiki.vex.tty.sh/wiki:computronics)  
[Project Red](https://minecraft.curseforge.com/projects/project-red-base)   
  

Originally from: https://github.com/whatthedrunk/allthemods/issues/327

**Comment by OrdinatorStouff** [comment]
Regarding the suggestion by @Dijkstra1 for mob grinding utils for a wither boss muffler, there is a config option `B:muteWither=true` in the mod "Animus" added after 1.0.31
