### ISSUE TITLE
Ender chest recipe in JEI with teleporter frame can't be made

### ISSUE THREAD

**Issue by Mason11987** [AllTheMods/ATM-Expert#71]
Recipe exists in JEI, but when placed in crafting tables (AE, or vanilla) it doesn't let you do the craft.

Thanks

**Comment by demethan** [comment]
Ditto

![image](https://user-images.githubusercontent.com/5810363/30619714-de4931e8-9d6e-11e7-9128-115f9b3d0aa3.png)

**Comment by demethan** [comment]
related.  https://github.com/AllTheMods/ATM-Expert/issues/63

**Comment by pyure** [comment]
Confirmed

**Comment by goosezilla** [comment]
should be fixed in latest version with new recipe waiting for confirmation
