### ISSUE TITLE
Can't hand in Pure Common princess

### ISSUE THREAD

**Issue by Mason11987** [AllTheMods/ATM-Expert#72]
I have a pure common princess (I had some of it's genes modified with the genetic imprinter) it's not letting me submit it.

**Comment by daph2511** [comment]
I have the same problem, how did you fixed it?

**Comment by Mason11987** [comment]
I realized I hadn't handed in the apiary quest yet.

**Comment by Mason11987** [comment]
Actually, it doesn't work.  Just got to the cultivated one, and my cultivated wouldn't work.  A cheated in princess (that was then scanned) worked though.

**Comment by Luckdemon** [comment]
Neither the common bee quest nor the lifespan-fertility template quests are completing for me. I have the Common bee as pure as is physically possible without cheating. (Bred through the advanced Mutatron)

**Comment by goosezilla** [comment]
new quest item should be fixed in version 1.1.1 waiting for confirmation
