### ISSUE TITLE
Extra Utilities 2 Mechanical Crafter crashes server

### ISSUE THREAD

**Issue by Samurai303** [AllTheMods/ATM-Expert#73]
Pack version 1.1.0
There appears to be an issue with the EU2 mechanical crafterm duplicable as follows in a clean world:

1. Place crafter
2. Attempt to add recipe
3. As soon as a valid recipe is hit, crash

Reloading the chunk will cause the crash again.

[crash-2017-09-05_21.41.24-server.txt](https://github.com/AllTheMods/ATM-Expert/files/1278856/crash-2017-09-05_21.41.24-server.txt)

[MultiMC Log](https://paste.ee/p/k2I0B)

**Comment by Boomflex** [comment]
Cannot reproduce.

Tested on 1.1.0 and the new 1.1.1

Please update the pack and try again.
