### ISSUE TITLE
Problems running any Shader

### ISSUE THREAD

**Issue by DySFunction** [AllTheMods/ATM-Expert#75]
running all the mods expert remastered, i cannot get a shader to work correct, any shader for that matter, i get screen flickering on the top half of the screen and/or its blue.  Specifically when i look above the horizon line. anyone have this issue or have a workaround for it?  I have updated java, and nividia drivers.   I have set Nvidia to handle openGL , and set power management mode to  max preformance in the nvidia control center.   Running a Nvida 1080 with 10gddr4 allocated to minecraft.  There is no crash log for me to submit, 

also on a side note, since updating java and nvidia drivers to the most current version i cannot go in fullscreen mode, or i get  a Open GL crash (why i tried a few of the steps above)

**Comment by Ricket** [comment]
It's probably due to Astral Sorcery's sky rendering. I don't think shaders generally work well in modded MC, especially not a kitchen sink pack like ATM. I would recommend not using shaders, but maybe someone will have a different solution.

**Comment by Boomflex** [comment]
Conflicting 3rd party mod.

Not a pack issue.
