### ISSUE TITLE
Rockhounding quest

### ISSUE THREAD

**Issue by drmorgmd** [AllTheMods/ATM-Expert#76]
The quest in rockhounding is for 4 induction heating interfaces however the image to the right (for detection task) is of rockhounding platinum ingot and there is no way of making the rockhounding version it just converts to the thermal version and the thermal version will not trigger the quest. 

I hope i am not doing anything wrong i have tried multiple ways to trigger it.

**Comment by benkibejs** [comment]
Just confirming, i have the same issue. Seems to be you that handles the HQM book --> @MigukNamja. Thx for a great pack :)

**Comment by Bulluk** [comment]
I had the same issue. I did not check if there already was an issue about this.
https://github.com/AllTheMods/ATM-Expert/issues/87

**Comment by Boomflex** [comment]
Fixed in v1.1.1

Please update pack.
