### ISSUE TITLE
Can't put naptha into carpenter to make plastic sheets

### ISSUE THREAD

**Issue by Mason11987** [AllTheMods/ATM-Expert#77]
Tried to put naptha in the carpenter with ender io conduits, with the openblocks tank, and with filled buckets, nothing works, meaning plastic sheets aren't craftable

**Comment by ScottRadish** [comment]
I came here to report this same issue. Can't make plastic.

**Comment by goosezilla** [comment]
Ive changed the recipe for the new version but I couldn't reproduce the bug of not being able to put naptha into the carpenter with either a bucket or conduit. I did however have issues with the open blocks tanks themselves so maybe the problem was with that.

**Comment by Boomflex** [comment]
Please update to v1.1.1 and let us know.
