### ISSUE TITLE
recipe conflict

### ISSUE THREAD

**Issue by demethan** [AllTheMods/ATM-Expert#78]
Hi, 

The botania alchemic recipe for blazerod --> embers conflicts with the botania recipe blazerod --> netherwarts.

throwing blazerods in the pool gives you netherwarts.

ATM2:ER 1.0.1

**Comment by Boomflex** [comment]
Fixed in 1.1.1

Changed from Blaze Rod to Blaze Powder.

![image](https://user-images.githubusercontent.com/22868795/31866413-f1ccad5e-b776-11e7-9b48-505f567dd88a.png)
