### ISSUE TITLE
SUGGESTION: Rockhounding Ores to ET Void Miner

### ISSUE THREAD

**Issue by OrdinatorStouff** [AllTheMods/ATM-Expert#80]
Suggestion:

Add Rockhounding Uninspected mineral to Void Ore Miner JSON (example below; note I may not have gotten the oredict exactly correct please confirm before implementing).

Also worth looking into adding rockhounding coals to the ore miner or perhaps the resource miner.

```json
{
    "oreName": "oreUninspected",
    "focusColor": "light_gray",
    "weight": 40
},

**Comment by Boomflex** [comment]
Done in 1.1.1
