### ISSUE TITLE
Can't make Diorite and Andesite block variants using the Chisel

### ISSUE THREAD

**Issue by ChaoticTabris** [AllTheMods/ATM-Expert#83]
For some reason when i put a Diorite or Andesite block on the chisel it only shows me normal stone variants instead of the specific variants for those blocks. Granite works fine.

**Comment by Boomflex** [comment]
Please update to v1.1.1

Confirmed working now.

![image](https://user-images.githubusercontent.com/22868795/31867932-6d2fc338-b78f-11e7-9569-c20e64722a1a.png)
