### ISSUE TITLE
Can't destroy blocks that don't require tools

### ISSUE THREAD

**Issue by SaschaRunge** [AllTheMods/ATM-Expert#85]
For some reason I can't destroy neither grass, sand, dirt or gravel without having the proper tool, while I can in fact destroy stone by hand. I am not in adventure mode. Earlier today everything just worked fine, have no clue what's causing this.

**Comment by SaschaRunge** [comment]
In fact, this is shared between worlds. Made a world for testing and the problem persists.

**Comment by Boomflex** [comment]
Not reproducible.

Please reinstall the pack and see if the problem persists.
