### ISSUE TITLE
Roots Acceleration wand and client crash

### ISSUE THREAD

**Issue by Itty0** [AllTheMods/ATM-Expert#9]
Every time I use acceleration wand in roots mod to ATM Rockhounding machines, such as mineral sizer, cause minecraft client crash. It seems to be working, but it always crush.
ATM Ex-ver.1.0.30; Roots-ver.0.208

**Comment by ghost** [comment]
Could I see the crash log please?

**Comment by Itty0** [comment]
May be my survival world data is strange...
Another creative world doesn't crash.

Crashreport is here.
[error_report.txt](https://github.com/AllTheMods/ATM-Expert/files/836010/error_report.txt)

**Comment by OrdinatorStouff** [comment]
I'm going to need some help testing this again in pack version 1.1.1+ since the roots staff isn't easily "cheatable" in. 

I just need to know if this is still an issue in 1.1.1+ pack ver
