### ISSUE TITLE
I can't craft Botanical Brewery

### ISSUE THREAD

**Issue by Iguan19** [AllTheMods/ATM-Expert#90]
Hello everybody!
I was trying to cast some runes for the blood magic mod so I needed a Vial of Crimson Shade for it. In order to get the Vials, I need the Botanical Brewery but, when I try to craft botanical brewery with the JEI recipe on a vanilla crafting table I get this:

This is the JEI recipe:

![clipboard01](https://user-images.githubusercontent.com/32722589/31473779-75d65282-aeab-11e7-89c2-a09cefbc666a.jpg)

This is what I get on the crafting table:

![clipboard02](https://user-images.githubusercontent.com/32722589/31473810-a79673e2-aeab-11e7-86bf-65ce43aed942.jpg)

When I try to craft it with the applied energetics crafting station I get this:

![clipboard03](https://user-images.githubusercontent.com/32722589/31473819-b143266a-aeab-11e7-9edc-7d8bcfa658a7.jpg)

But I can't take the item from the station. I have tried to craft all the ingredients again and didn't work.
I tried it on versions 1.0.33b and 1.1.1.

Thanks!

**Comment by Boomflex** [comment]
Hello there,

I have tested this on 1.1.0 that is the current latest version of the pack and it works.

![image](https://user-images.githubusercontent.com/22868795/31866191-af0aa38e-b773-11e7-8e7b-c31abbefb0b5.png)

I can take that out of the crafting grid and use it.

**Comment by goosezilla** [comment]
Change it to match the recipe in Remastered. 

//=====Botanical Brewery =====
recipes.remove(<botania:brewery>);
recipes.addShaped(<botania:brewery>,
[[<bloodmagic:ItemSlate>,<bloodmagic:BlockIncenseAltar>,<bloodmagic:ItemSlate>],
 [<botania:manaResource:22>,<botania:rune:8>,<botania:manaResource:22>],
 [<botania:livingrock>,<botania:storage>,<botania:livingrock>]]);
