### ISSUE TITLE
Creosote Oil unusable and texture bad.

### ISSUE THREAD

**Issue by TraviAdpet** [AllTheMods/ATM-Expert#93]
Coke oven creosote oil is not useable and the texture is bad.

https://imgur.com/a/D9Blc

**Comment by goosezilla** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/2550

Appears to be an IE issue, i'll look into a fix

edit:
try changing the value for creosote to false for railcraft like:

fluids {
    B:creosote=false
    B:steam=true
}
in the config/railcraft/railcraft.cfg and let me know if that fixes the problem as it worked for me.

**Comment by irvine1231** [comment]
I have the same problem.
I have already change creosote to false on both client side and server side, but it still doesn't work.
Is there any other ways to fix it?

**Comment by TraviAdpet** [comment]
On my existing world after disabling rail craft creosote(on client and server) the IE creosote still does not work. This is important because you can't make treated wood which is needed to make living wood.

**Comment by goosezilla** [comment]
Try what was suggested in the IE thread.

**Comment by TraviAdpet** [comment]
not to sound stupid but how does one remove an item from the registy

**Comment by goosezilla** [comment]
https://github.com/BluSunrize/ImmersiveEngineering/issues/1880 
This thread has more useful info, last comment is what you're looking for I think.

**Comment by irvine1231** [comment]
There's no thermalfoundation:creosote in my level.dat's DefaultFluidList, I only find immersiveengineering:creosote in it, but things still go wrong.

**Comment by goosezilla** [comment]
is there an entry for the railcraft creosote?

**Comment by irvine1231** [comment]
I fixed it by changing immersiveengineering:creosote into thermalfoundation:creosote. So weird, thanks for your help.  👍

**Comment by Ravalli03** [comment]
@irvine1231, where do I find the file to change it? I changed the railcraft setting, but I'm still not able to pick up the fluid with a bucket. Thanks for any help.

**Comment by TraviAdpet** [comment]
look for it in the world folder

**Comment by Ravalli03** [comment]
@TraviAdpet found it and figured out how to fix it. Thanks
