### ISSUE TITLE
Jetpacks do not provide armor or textures

### ISSUE THREAD

**Issue by TraviAdpet** [AllTheMods/ATM-Expert#96]
current version 1.1.1
been happening since before the update.

https://imgur.com/a/J1wqc

Edit: issue happens with simply jetpacks but not IC2

**Comment by Boomflex** [comment]
Known bugs for Simply Jetpacks 2.

No Armour: https://github.com/Tomson124/SimplyJetpacks-2/issues/42

No Textures: https://github.com/Tomson124/SimplyJetpacks-2/issues/36#issuecomment-321345547

Will need mod update to fix.

Not a pack issue.
