### ISSUE TITLE
Salt / Coal Coke in Lab Blender 

### ISSUE THREAD

**Issue by dingsbums** [AllTheMods/ATM-Expert#98]
Hi,

the salt I am making with the Seasoning Rack does not work in the Lab Blender.
Also Coal coke (also Block of coal coke) from the Coke Oven does not make Carbon Compost.

**Comment by goosezilla** [comment]
I'll look into for next update as I can _maybe_ fix this by oredicting the salt and coal cokes but again this is almost certainly a bug within the mod as i've not touched any recipes for either machine.
